service: calculator-tn-api
frameworkVersion: '3'

plugins:
 - serverless-offline

provider:
  name: aws
  runtime: nodejs18.x
  memorySize: 128
  timeout: 10
  tracing:
    lambda: true
  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1
    JWT_HS256_KEY: ${param:jwtKey}
    RANDOM_ORG_API_KEY: ${param:randomOrgApiKey}

functions:
  authorizeRequest:
    handler: app.authorizeRequest
  auth:
    handler: app.auth
    events:
      - http:
          path: /v1/auth
          method: POST
  register:
    handler: app.register
    events:
      - http:
          path: /v1/register
          method: POST
  calculateBasic:
    handler: app.calculateBasic
    events:
      - http:
          path: /v1/calculate/basic
          method: POST
          authorizer:
            name: authorizeRequest
            identitySource: method.request.header.Authorization
            resultTtlInSeconds: 3600
  calculateRandom:
    handler: app.calculateRandom
    events:
      - http:
          path: /v1/calculate/random
          method: POST
          authorizer:
            name: authorizeRequest
            identitySource: method.request.header.Authorization
            resultTtlInSeconds: 3600
